export default [  
  {  
    "id":9267,
    "url":"https://yts.am/movie/easter-bunny-adventure-2017",
    "imdb_code":"tt6408946",
    "title":"Easter Bunny Adventure",
    "title_english":"Easter Bunny Adventure",
    "title_long":"Easter Bunny Adventure (2017)",
    "slug":"easter-bunny-adventure-2017",
    "year":2017,
    "rating":3.1,
    "runtime":74,
    "genres":[  
      "Animation"
    ],
    "summary":"The Easter Bunny looking for the best Easter Egg, on his way to find it, he runs into friends and they tell him different fables.",
    "description_full":"The Easter Bunny looking for the best Easter Egg, on his way to find it, he runs into friends and they tell him different fables.",
    "synopsis":"The Easter Bunny looking for the best Easter Egg, on his way to find it, he runs into friends and they tell him different fables.",
    "yt_trailer_code":"ZVfOvRjiE60",
    "language":"English",
    "mpa_rating":"",
    "background_image":"https://yts.am/assets/images/movies/easter_bunny_adventure_2017/background.jpg",
    "background_image_original":"https://yts.am/assets/images/movies/easter_bunny_adventure_2017/background.jpg",
    "small_cover_image":"https://yts.am/assets/images/movies/easter_bunny_adventure_2017/small-cover.jpg",
    "medium_cover_image":"https://yts.am/assets/images/movies/easter_bunny_adventure_2017/medium-cover.jpg",
    "large_cover_image":"https://yts.am/assets/images/movies/easter_bunny_adventure_2017/large-cover.jpg",
    "state":"ok",
    "torrents":[  
      {  
          "url":"https://yts.am/torrent/download/89AF982813BBF64B66D179A4BE1D0E1AB697C3C7",
          "hash":"89AF982813BBF64B66D179A4BE1D0E1AB697C3C7",
          "quality":"720p",
          "seeds":0,
          "peers":0,
          "size":"627.42 MB",
          "size_bytes":657897554,
          "date_uploaded":"2018-10-10 16:10:34",
          "date_uploaded_unix":1539180634
      }
    ],
    "date_uploaded":"2018-10-10 16:10:34",
    "date_uploaded_unix":1539180634
},
{  
    "id":9266,
    "url":"https://yts.am/movie/mine-own-executioner-1947",
    "imdb_code":"tt0039627",
    "title":"Mine Own Executioner",
    "title_english":"Mine Own Executioner",
    "title_long":"Mine Own Executioner (1947)",
    "slug":"mine-own-executioner-1947",
    "year":1947,
    "rating":7,
    "runtime":108,
    "genres":[  
      "Drama",
      "Thriller"
    ],
    "summary":"Pretty Molly Lucian enlists the reluctant aid of psychologist Felix Milne in treating her potentially homicidal husband Adam, who refuses to see a \"real\" psychiatrist. Traumatized in a Japanese prison camp, Adam proves to be on the verge of severe schizophrenia. In his risky struggle to help Adam, Felix finds his none-too-functional home life deteriorating, and is unable to help himself as he helps others. The situation rushes headlong to a suspenseful climax...",
    "description_full":"Pretty Molly Lucian enlists the reluctant aid of psychologist Felix Milne in treating her potentially homicidal husband Adam, who refuses to see a \"real\" psychiatrist. Traumatized in a Japanese prison camp, Adam proves to be on the verge of severe schizophrenia. In his risky struggle to help Adam, Felix finds his none-too-functional home life deteriorating, and is unable to help himself as he helps others. The situation rushes headlong to a suspenseful climax...",
    "synopsis":"Pretty Molly Lucian enlists the reluctant aid of psychologist Felix Milne in treating her potentially homicidal husband Adam, who refuses to see a \"real\" psychiatrist. Traumatized in a Japanese prison camp, Adam proves to be on the verge of severe schizophrenia. In his risky struggle to help Adam, Felix finds his none-too-functional home life deteriorating, and is unable to help himself as he helps others. The situation rushes headlong to a suspenseful climax...",
    "yt_trailer_code":"",
    "language":"English",
    "mpa_rating":"",
    "background_image":"https://yts.am/assets/images/movies/mine_own_executioner_1947/background.jpg",
    "background_image_original":"https://yts.am/assets/images/movies/mine_own_executioner_1947/background.jpg",
    "small_cover_image":"https://yts.am/assets/images/movies/mine_own_executioner_1947/small-cover.jpg",
    "medium_cover_image":"https://yts.am/assets/images/movies/mine_own_executioner_1947/medium-cover.jpg",
    "large_cover_image":"https://yts.am/assets/images/movies/mine_own_executioner_1947/large-cover.jpg",
    "state":"ok",
    "torrents":[  
      {  
          "url":"https://yts.am/torrent/download/212B5858D9B74EBE7D22FF04214F6B793A4DAB5D",
          "hash":"212B5858D9B74EBE7D22FF04214F6B793A4DAB5D",
          "quality":"720p",
          "seeds":25,
          "peers":62,
          "size":"921.27 MB",
          "size_bytes":966021612,
          "date_uploaded":"2018-10-10 11:33:44",
          "date_uploaded_unix":1539164024
      },
      {  
          "url":"https://yts.am/torrent/download/795BE304377436635EA1EB85692671CC1101FE80",
          "hash":"795BE304377436635EA1EB85692671CC1101FE80",
          "quality":"1080p",
          "seeds":0,
          "peers":0,
          "size":"1.74 GB",
          "size_bytes":1868310774,
          "date_uploaded":"2018-10-10 13:46:43",
          "date_uploaded_unix":1539172003
      }
    ],
    "date_uploaded":"2018-10-10 11:33:44",
    "date_uploaded_unix":1539164024
},
{  
    "id":9265,
    "url":"https://yts.am/movie/teen-titans-go-to-the-movies-2018",
    "imdb_code":"tt7424200",
    "title":"Teen Titans Go! To the Movies",
    "title_english":"Teen Titans Go! To the Movies",
    "title_long":"Teen Titans Go! To the Movies (2018)",
    "slug":"teen-titans-go-to-the-movies-2018",
    "year":2018,
    "rating":6.8,
    "runtime":84,
    "genres":[  
      "Action",
      "Animation",
      "Comedy",
      "Family",
      "Musical",
      "Sci-Fi"
    ],
    "summary":"It seems to the Teens that all the major superheroes out there are starring in their own movies-everyone but the Teen Titans, that is. But de facto leader Robin is determined to remedy the situation, and be seen as a star instead of a sidekick. If only they could get the hottest Hollywood film director to notice them. With a few madcap ideas and a song in their heart, the Teen Titans head to Tinsel Town, certain to pull off their dream. But when the group is radically misdirected by a seriously super villain and his maniacal plan to take over the Earth, things really go awry. The team finds their friendship and their fighting spirit failing, putting the very fate of the Teen Titans themselves on the line.",
    "description_full":"It seems to the Teens that all the major superheroes out there are starring in their own movies-everyone but the Teen Titans, that is. But de facto leader Robin is determined to remedy the situation, and be seen as a star instead of a sidekick. If only they could get the hottest Hollywood film director to notice them. With a few madcap ideas and a song in their heart, the Teen Titans head to Tinsel Town, certain to pull off their dream. But when the group is radically misdirected by a seriously super villain and his maniacal plan to take over the Earth, things really go awry. The team finds their friendship and their fighting spirit failing, putting the very fate of the Teen Titans themselves on the line.",
    "synopsis":"It seems to the Teens that all the major superheroes out there are starring in their own movies-everyone but the Teen Titans, that is. But de facto leader Robin is determined to remedy the situation, and be seen as a star instead of a sidekick. If only they could get the hottest Hollywood film director to notice them. With a few madcap ideas and a song in their heart, the Teen Titans head to Tinsel Town, certain to pull off their dream. But when the group is radically misdirected by a seriously super villain and his maniacal plan to take over the Earth, things really go awry. The team finds their friendship and their fighting spirit failing, putting the very fate of the Teen Titans themselves on the line.",
    "yt_trailer_code":"1sqYpN1oxmg",
    "language":"English",
    "mpa_rating":"PG",
    "background_image":"https://yts.am/assets/images/movies/teen_titans_go_to_the_movies_2018/background.jpg",
    "background_image_original":"https://yts.am/assets/images/movies/teen_titans_go_to_the_movies_2018/background.jpg",
    "small_cover_image":"https://yts.am/assets/images/movies/teen_titans_go_to_the_movies_2018/small-cover.jpg",
    "medium_cover_image":"https://yts.am/assets/images/movies/teen_titans_go_to_the_movies_2018/medium-cover.jpg",
    "large_cover_image":"https://yts.am/assets/images/movies/teen_titans_go_to_the_movies_2018/large-cover.jpg",
    "state":"ok",
    "torrents":[  
      {  
          "url":"https://yts.am/torrent/download/3DAF237B291193EEBB08222F637BB6AF689E23D3",
          "hash":"3DAF237B291193EEBB08222F637BB6AF689E23D3",
          "quality":"720p",
          "seeds":195,
          "peers":584,
          "size":"711.84 MB",
          "size_bytes":746418340,
          "date_uploaded":"2018-10-10 11:09:07",
          "date_uploaded_unix":1539162547
      },
      {  
          "url":"https://yts.am/torrent/download/47E77C1720B9556DD6D3DB267C28EDA237C8467F",
          "hash":"47E77C1720B9556DD6D3DB267C28EDA237C8467F",
          "quality":"1080p",
          "seeds":0,
          "peers":0,
          "size":"1.34 GB",
          "size_bytes":1438814044,
          "date_uploaded":"2018-10-10 12:32:44",
          "date_uploaded_unix":1539167564
      }
    ],
    "date_uploaded":"2018-10-10 11:09:07",
    "date_uploaded_unix":1539162547
},
{  
    "id":9264,
    "url":"https://yts.am/movie/its-not-the-size-that-counts-1974",
    "imdb_code":"tt0071677",
    "title":"It's Not the Size That Counts",
    "title_english":"It's Not the Size That Counts",
    "title_long":"It's Not the Size That Counts (1974)",
    "slug":"its-not-the-size-that-counts-1974",
    "year":1974,
    "rating":3.7,
    "runtime":0,
    "genres":[  
      "Action"
    ],
    "summary":"",
    "description_full":"",
    "synopsis":"",
    "yt_trailer_code":"7pmUJ8vOu18",
    "language":"English",
    "mpa_rating":"",
    "background_image":"https://yts.am/assets/images/movies/its_not_the_size_that_counts_1974/background.jpg",
    "background_image_original":"https://yts.am/assets/images/movies/its_not_the_size_that_counts_1974/background.jpg",
    "small_cover_image":"https://yts.am/assets/images/movies/its_not_the_size_that_counts_1974/small-cover.jpg",
    "medium_cover_image":"https://yts.am/assets/images/movies/its_not_the_size_that_counts_1974/medium-cover.jpg",
    "large_cover_image":"https://yts.am/assets/images/movies/its_not_the_size_that_counts_1974/large-cover.jpg",
    "state":"ok",
    "torrents":[  
      {  
          "url":"https://yts.am/torrent/download/EC0B37BD020BA43C595F52C39D1EC6BAD7990017",
          "hash":"EC0B37BD020BA43C595F52C39D1EC6BAD7990017",
          "quality":"720p",
          "seeds":179,
          "peers":158,
          "size":"851.97 MB",
          "size_bytes":893355295,
          "date_uploaded":"2018-10-10 07:12:30",
          "date_uploaded_unix":1539148350
      },
      {  
          "url":"https://yts.am/torrent/download/7D31B9F8C7548FC004212EEB64F3CBAFEAE9935A",
          "hash":"7D31B9F8C7548FC004212EEB64F3CBAFEAE9935A",
          "quality":"1080p",
          "seeds":106,
          "peers":95,
          "size":"1.61 GB",
          "size_bytes":1728724337,
          "date_uploaded":"2018-10-10 09:44:10",
          "date_uploaded_unix":1539157450
      }
    ],
    "date_uploaded":"2018-10-10 07:12:30",
    "date_uploaded_unix":1539148350
},
{  
    "id":9263,
    "url":"https://yts.am/movie/the-witch-files-2018",
    "imdb_code":"tt4580550",
    "title":"The Witch Files",
    "title_english":"The Witch Files",
    "title_long":"The Witch Files (2018)",
    "slug":"the-witch-files-2018",
    "year":2018,
    "rating":4.4,
    "runtime":87,
    "genres":[  
      "Horror",
      "Thriller"
    ],
    "summary":"A group of marginalized young women form a powerful coven.",
    "description_full":"A group of marginalized young women form a powerful coven.",
    "synopsis":"A group of marginalized young women form a powerful coven.",
    "yt_trailer_code":"t97nwmyHduc",
    "language":"English",
    "mpa_rating":"",
    "background_image":"https://yts.am/assets/images/movies/the_witch_files_2018/background.jpg",
    "background_image_original":"https://yts.am/assets/images/movies/the_witch_files_2018/background.jpg",
    "small_cover_image":"https://yts.am/assets/images/movies/the_witch_files_2018/small-cover.jpg",
    "medium_cover_image":"https://yts.am/assets/images/movies/the_witch_files_2018/medium-cover.jpg",
    "large_cover_image":"https://yts.am/assets/images/movies/the_witch_files_2018/large-cover.jpg",
    "state":"ok",
    "torrents":[  
      {  
          "url":"https://yts.am/torrent/download/C2CCE6EB91D69D70B4B7D74F9A558799D5A46265",
          "hash":"C2CCE6EB91D69D70B4B7D74F9A558799D5A46265",
          "quality":"720p",
          "seeds":1071,
          "peers":1175,
          "size":"742.95 MB",
          "size_bytes":779039539,
          "date_uploaded":"2018-10-10 02:51:09",
          "date_uploaded_unix":1539132669
      },
      {  
          "url":"https://yts.am/torrent/download/966D74EF6F7AE2A2FACEC3D01BE7BE0B0AAD6D8F",
          "hash":"966D74EF6F7AE2A2FACEC3D01BE7BE0B0AAD6D8F",
          "quality":"1080p",
          "seeds":609,
          "peers":599,
          "size":"1.4 GB",
          "size_bytes":1503238554,
          "date_uploaded":"2018-10-10 04:33:51",
          "date_uploaded_unix":1539138831
      }
    ],
    "date_uploaded":"2018-10-10 02:51:09",
    "date_uploaded_unix":1539132669
},
{  
    "id":9262,
    "url":"https://yts.am/movie/a-man-about-the-house-1947",
    "imdb_code":"tt0039600",
    "title":"A Man About the House",
    "title_english":"A Man About the House",
    "title_long":"A Man About the House (1947)",
    "slug":"a-man-about-the-house-1947",
    "year":1947,
    "rating":6.6,
    "runtime":99,
    "summary":"Agnes and Ellen Isit, two poor English sisters, unexpectedly inherit from their uncle a rich estate near Naples, complete with big villa and manly Italian majordomo. The latter, Salvatore, makes use of his Latin charm to seduce Agnes, who soon turns from prim spinster to passionate lover. Ellen observes the romance with amusement first before realizing how little considerate Salvatore becomes after marrying Agnes. Worse, Agnes's health starts deteriorating. Worried about her sister, she contacts Dr. Ben Dench, a family friend...",
    "description_full":"Agnes and Ellen Isit, two poor English sisters, unexpectedly inherit from their uncle a rich estate near Naples, complete with big villa and manly Italian majordomo. The latter, Salvatore, makes use of his Latin charm to seduce Agnes, who soon turns from prim spinster to passionate lover. Ellen observes the romance with amusement first before realizing how little considerate Salvatore becomes after marrying Agnes. Worse, Agnes's health starts deteriorating. Worried about her sister, she contacts Dr. Ben Dench, a family friend...",
    "synopsis":"Agnes and Ellen Isit, two poor English sisters, unexpectedly inherit from their uncle a rich estate near Naples, complete with big villa and manly Italian majordomo. The latter, Salvatore, makes use of his Latin charm to seduce Agnes, who soon turns from prim spinster to passionate lover. Ellen observes the romance with amusement first before realizing how little considerate Salvatore becomes after marrying Agnes. Worse, Agnes's health starts deteriorating. Worried about her sister, she contacts Dr. Ben Dench, a family friend...",
    "yt_trailer_code":"",
    "language":"English",
    "mpa_rating":"",
    "background_image":"https://yts.am/assets/images/movies/a_man_about_the_house_1947/background.jpg",
    "background_image_original":"https://yts.am/assets/images/movies/a_man_about_the_house_1947/background.jpg",
    "small_cover_image":"https://yts.am/assets/images/movies/a_man_about_the_house_1947/small-cover.jpg",
    "medium_cover_image":"https://yts.am/assets/images/movies/a_man_about_the_house_1947/medium-cover.jpg",
    "large_cover_image":"https://yts.am/assets/images/movies/a_man_about_the_house_1947/large-cover.jpg",
    "state":"ok",
    "torrents":[  
      {  
          "url":"https://yts.am/torrent/download/C75A19634A0F8968D6C7B26194BD423A792A59A9",
          "hash":"C75A19634A0F8968D6C7B26194BD423A792A59A9",
          "quality":"720p",
          "seeds":62,
          "peers":32,
          "size":"775.64 MB",
          "size_bytes":813317489,
          "date_uploaded":"2018-10-10 03:57:24",
          "date_uploaded_unix":1539136644
      },
      {  
          "url":"https://yts.am/torrent/download/0D1AFB038A335950BBAE1F761AA4043022AC53E4",
          "hash":"0D1AFB038A335950BBAE1F761AA4043022AC53E4",
          "quality":"1080p",
          "seeds":68,
          "peers":126,
          "size":"1.48 GB",
          "size_bytes":1589137900,
          "date_uploaded":"2018-10-10 05:54:35",
          "date_uploaded_unix":1539143675
      }
    ],
    "date_uploaded":"2018-10-10 03:57:24",
    "date_uploaded_unix":1539136644
},
{  
    "id":9260,
    "url":"https://yts.am/movie/down-on-the-farm-2017",
    "imdb_code":"tt6407390",
    "title":"Down on the Farm",
    "title_english":"Down on the Farm",
    "title_long":"Down on the Farm (2017)",
    "slug":"down-on-the-farm-2017",
    "year":2017,
    "rating":4.6,
    "runtime":72,
    "genres":[  
      "Animation"
    ],
    "summary":"When a bale of hay goes missing on the farm, only one animal can solve this mystery: OINK, the FLYING PIG!",
    "description_full":"When a bale of hay goes missing on the farm, only one animal can solve this mystery: OINK, the FLYING PIG!",
    "synopsis":"When a bale of hay goes missing on the farm, only one animal can solve this mystery: OINK, the FLYING PIG!",
    "yt_trailer_code":"FTj8k6nsuzk",
    "language":"English",
    "mpa_rating":"",
    "background_image":"https://yts.am/assets/images/movies/down_on_the_farm_2017/background.jpg",
    "background_image_original":"https://yts.am/assets/images/movies/down_on_the_farm_2017/background.jpg",
    "small_cover_image":"https://yts.am/assets/images/movies/down_on_the_farm_2017/small-cover.jpg",
    "medium_cover_image":"https://yts.am/assets/images/movies/down_on_the_farm_2017/medium-cover.jpg",
    "large_cover_image":"https://yts.am/assets/images/movies/down_on_the_farm_2017/large-cover.jpg",
    "state":"ok",
    "torrents":[  
      {  
          "url":"https://yts.am/torrent/download/223A320A64B12A1837CB6699CAE828F621A267D8",
          "hash":"223A320A64B12A1837CB6699CAE828F621A267D8",
          "quality":"720p",
          "seeds":379,
          "peers":375,
          "size":"605.31 MB",
          "size_bytes":634713539,
          "date_uploaded":"2018-10-10 00:39:16",
          "date_uploaded_unix":1539124756
      },
      {  
          "url":"https://yts.am/torrent/download/DD3A0EBFD8CE24AA5641E71887635C6241182630",
          "hash":"DD3A0EBFD8CE24AA5641E71887635C6241182630",
          "quality":"1080p",
          "seeds":314,
          "peers":199,
          "size":"1.14 GB",
          "size_bytes":1224065679,
          "date_uploaded":"2018-10-10 01:54:07",
          "date_uploaded_unix":1539129247
      }
    ],
    "date_uploaded":"2018-10-10 00:39:16",
    "date_uploaded_unix":1539124756
},
{  
    "id":9259,
    "url":"https://yts.am/movie/mamma-mia-here-we-go-again-2018",
    "imdb_code":"tt6911608",
    "title":"Mamma Mia! Here We Go Again",
    "title_english":"Mamma Mia! Here We Go Again",
    "title_long":"Mamma Mia! Here We Go Again (2018)",
    "slug":"mamma-mia-here-we-go-again-2018",
    "year":2018,
    "rating":7.1,
    "runtime":114,
    "genres":[  
      "Comedy",
      "Musical",
      "Romance"
    ],
    "summary":"Discover Donna's (Meryl Streep, Lily James) young life, experiencing the fun she had with the three possible dads of Sophie (Amanda Seyfriend). As she reflects on her mom's journey, Sophie finds herself to be more like her mother than she ever even realized.",
    "description_full":"Discover Donna's (Meryl Streep, Lily James) young life, experiencing the fun she had with the three possible dads of Sophie (Amanda Seyfriend). As she reflects on her mom's journey, Sophie finds herself to be more like her mother than she ever even realized.",
    "synopsis":"Discover Donna's (Meryl Streep, Lily James) young life, experiencing the fun she had with the three possible dads of Sophie (Amanda Seyfriend). As she reflects on her mom's journey, Sophie finds herself to be more like her mother than she ever even realized.",
    "yt_trailer_code":"XcSMdhfKga4",
    "language":"English",
    "mpa_rating":"",
    "background_image":"https://yts.am/assets/images/movies/mamma_mia_here_we_go_again_2018/background.jpg",
    "background_image_original":"https://yts.am/assets/images/movies/mamma_mia_here_we_go_again_2018/background.jpg",
    "small_cover_image":"https://yts.am/assets/images/movies/mamma_mia_here_we_go_again_2018/small-cover.jpg",
    "medium_cover_image":"https://yts.am/assets/images/movies/mamma_mia_here_we_go_again_2018/medium-cover.jpg",
    "large_cover_image":"https://yts.am/assets/images/movies/mamma_mia_here_we_go_again_2018/large-cover.jpg",
    "state":"ok",
    "torrents":[  
      {  
          "url":"https://yts.am/torrent/download/AF4B0BB3E7688C05F0A6AD920819DAD7AFFE5405",
          "hash":"AF4B0BB3E7688C05F0A6AD920819DAD7AFFE5405",
          "quality":"720p",
          "seeds":3120,
          "peers":3136,
          "size":"962.63 MB",
          "size_bytes":1009390715,
          "date_uploaded":"2018-10-09 21:55:24",
          "date_uploaded_unix":1539114924
      },
      {  
          "url":"https://yts.am/torrent/download/A435BCD46547217C72C74691910A36AA6EAE75A4",
          "hash":"A435BCD46547217C72C74691910A36AA6EAE75A4",
          "quality":"1080p",
          "seeds":2416,
          "peers":2266,
          "size":"1.81 GB",
          "size_bytes":1943472701,
          "date_uploaded":"2018-10-09 23:52:10",
          "date_uploaded_unix":1539121930
      }
    ],
    "date_uploaded":"2018-10-09 21:55:24",
    "date_uploaded_unix":1539114924
},
{  
    "id":9258,
    "url":"https://yts.am/movie/sorry-to-bother-you-2018",
    "imdb_code":"tt5688932",
    "title":"Sorry to Bother You",
    "title_english":"Sorry to Bother You",
    "title_long":"Sorry to Bother You (2018)",
    "slug":"sorry-to-bother-you-2018",
    "year":2018,
    "rating":7.4,
    "runtime":111,
    "genres":[  
      "Comedy",
      "Fantasy",
      "Sci-Fi"
    ],
    "summary":"In an alternate version of Oakland, Cassius Green gets a telemarketing job and finds the commission paid job a dispiriting struggle as a black man selling to predominately white people over the phone. That changes when a veteran advises him to use his \"white voice,\" and the attitude behind it to make himself more appealing to customers. With a bizarrely high-pitched accent, Cassius becomes a success even as his colleagues form a union to improve their miserable jobs. Regardless, Cassius finds himself promoted a \"Power Caller\" selling the most morally abhorrent but lucrative products and services as his connection to his girlfriend and colleagues fades away. However, Cassius' conscience arises anew as he finds himself in the midst of his boss' bizarre world of condescending bigoted decadence and his sinister plans to create the perfect subservient work force with Cassius' help.",
    "description_full":"In an alternate version of Oakland, Cassius Green gets a telemarketing job and finds the commission paid job a dispiriting struggle as a black man selling to predominately white people over the phone. That changes when a veteran advises him to use his \"white voice,\" and the attitude behind it to make himself more appealing to customers. With a bizarrely high-pitched accent, Cassius becomes a success even as his colleagues form a union to improve their miserable jobs. Regardless, Cassius finds himself promoted a \"Power Caller\" selling the most morally abhorrent but lucrative products and services as his connection to his girlfriend and colleagues fades away. However, Cassius' conscience arises anew as he finds himself in the midst of his boss' bizarre world of condescending bigoted decadence and his sinister plans to create the perfect subservient work force with Cassius' help.",
    "synopsis":"In an alternate version of Oakland, Cassius Green gets a telemarketing job and finds the commission paid job a dispiriting struggle as a black man selling to predominately white people over the phone. That changes when a veteran advises him to use his \"white voice,\" and the attitude behind it to make himself more appealing to customers. With a bizarrely high-pitched accent, Cassius becomes a success even as his colleagues form a union to improve their miserable jobs. Regardless, Cassius finds himself promoted a \"Power Caller\" selling the most morally abhorrent but lucrative products and services as his connection to his girlfriend and colleagues fades away. However, Cassius' conscience arises anew as he finds himself in the midst of his boss' bizarre world of condescending bigoted decadence and his sinister plans to create the perfect subservient work force with Cassius' help.",
    "yt_trailer_code":"enH3xA4mYcY",
    "language":"English",
    "mpa_rating":"R",
    "background_image":"https://yts.am/assets/images/movies/sorry_to_bother_you_2018/background.jpg",
    "background_image_original":"https://yts.am/assets/images/movies/sorry_to_bother_you_2018/background.jpg",
    "small_cover_image":"https://yts.am/assets/images/movies/sorry_to_bother_you_2018/small-cover.jpg",
    "medium_cover_image":"https://yts.am/assets/images/movies/sorry_to_bother_you_2018/medium-cover.jpg",
    "large_cover_image":"https://yts.am/assets/images/movies/sorry_to_bother_you_2018/large-cover.jpg",
    "state":"ok",
    "torrents":[  
      {  
          "url":"https://yts.am/torrent/download/082D87696DE7740C4C498715B2352185DBAD5579",
          "hash":"082D87696DE7740C4C498715B2352185DBAD5579",
          "quality":"720p",
          "seeds":1802,
          "peers":1533,
          "size":"935.85 MB",
          "size_bytes":981309850,
          "date_uploaded":"2018-10-09 22:16:14",
          "date_uploaded_unix":1539116174
      },
      {  
          "url":"https://yts.am/torrent/download/A34FB63374C3854B90F610B182A32A705737FFCF",
          "hash":"A34FB63374C3854B90F610B182A32A705737FFCF",
          "quality":"1080p",
          "seeds":7,
          "peers":3307,
          "size":"1.77 GB",
          "size_bytes":1900523028,
          "date_uploaded":"2018-10-09 23:59:59",
          "date_uploaded_unix":1539122399
      }
    ],
    "date_uploaded":"2018-10-09 22:16:14",
    "date_uploaded_unix":1539116174
},
{  
    "id":9257,
    "url":"https://yts.am/movie/between-worlds-2018",
    "imdb_code":"tt7295450",
    "title":"Between Worlds",
    "title_english":"Between Worlds",
    "title_long":"Between Worlds (2018)",
    "slug":"between-worlds-2018",
    "year":2018,
    "rating":5.5,
    "runtime":90,
    "genres":[  
      "Action",
      "Mystery",
      "Thriller"
    ],
    "summary":"The story follows Joe, (Cage), a down-on-his-luck truck driver haunted by the memory of his deceased wife and child. He meets Julie (Potente), a spiritually gifted woman who enlists Joe in a desperate effort to find the lost soul of her comatose daughter, Billie (Mitchell). But the spirit of Joe's dead wife Mary proves stronger, possessing the young woman's body and determined to settle her unfinished business with the living.",
    "description_full":"The story follows Joe, (Cage), a down-on-his-luck truck driver haunted by the memory of his deceased wife and child. He meets Julie (Potente), a spiritually gifted woman who enlists Joe in a desperate effort to find the lost soul of her comatose daughter, Billie (Mitchell). But the spirit of Joe's dead wife Mary proves stronger, possessing the young woman's body and determined to settle her unfinished business with the living.",
    "synopsis":"The story follows Joe, (Cage), a down-on-his-luck truck driver haunted by the memory of his deceased wife and child. He meets Julie (Potente), a spiritually gifted woman who enlists Joe in a desperate effort to find the lost soul of her comatose daughter, Billie (Mitchell). But the spirit of Joe's dead wife Mary proves stronger, possessing the young woman's body and determined to settle her unfinished business with the living.",
    "yt_trailer_code":"",
    "language":"English",
    "mpa_rating":"",
    "background_image":"https://yts.am/assets/images/movies/between_worlds_2018/background.jpg",
    "background_image_original":"https://yts.am/assets/images/movies/between_worlds_2018/background.jpg",
    "small_cover_image":"https://yts.am/assets/images/movies/between_worlds_2018/small-cover.jpg",
    "medium_cover_image":"https://yts.am/assets/images/movies/between_worlds_2018/medium-cover.jpg",
    "large_cover_image":"https://yts.am/assets/images/movies/between_worlds_2018/large-cover.jpg",
    "state":"ok",
    "torrents":[  
      {  
          "url":"https://yts.am/torrent/download/6408BF5A4288F89799F46646DBAAF5FABF586E7B",
          "hash":"6408BF5A4288F89799F46646DBAAF5FABF586E7B",
          "quality":"720p",
          "seeds":995,
          "peers":783,
          "size":"773.62 MB",
          "size_bytes":811199365,
          "date_uploaded":"2018-10-09 19:38:22",
          "date_uploaded_unix":1539106702
      },
      {  
          "url":"https://yts.am/torrent/download/2D3B71960A0B64F42129AB6CCE7B8EB4BFB8EC7E",
          "hash":"2D3B71960A0B64F42129AB6CCE7B8EB4BFB8EC7E",
          "quality":"1080p",
          "seeds":681,
          "peers":440,
          "size":"1.45 GB",
          "size_bytes":1556925645,
          "date_uploaded":"2018-10-09 21:21:54",
          "date_uploaded_unix":1539112914
      }
    ],
    "date_uploaded":"2018-10-09 19:38:22",
    "date_uploaded_unix":1539106702
},
{  
    "id":9256,
    "url":"https://yts.am/movie/never-goin-back-2018",
    "imdb_code":"tt7690016",
    "title":"Never Goin' Back",
    "title_english":"Never Goin' Back",
    "title_long":"Never Goin' Back (2018)",
    "slug":"never-goin-back-2018",
    "year":2018,
    "rating":5.7,
    "runtime":85,
    "genres":[  
      "Comedy",
      "Crime",
      "Drama"
    ],
    "summary":"Jessie and Angela, high school dropout BFFs, are taking a week off to chill at the beach. Too bad their house got robbed, rent's due, they're about to get fired, and they're broke. Now they've gotta avoid eviction, stay out of jail and get to the beach, no matter what.",
    "description_full":"Jessie and Angela, high school dropout BFFs, are taking a week off to chill at the beach. Too bad their house got robbed, rent's due, they're about to get fired, and they're broke. Now they've gotta avoid eviction, stay out of jail and get to the beach, no matter what.",
    "synopsis":"Jessie and Angela, high school dropout BFFs, are taking a week off to chill at the beach. Too bad their house got robbed, rent's due, they're about to get fired, and they're broke. Now they've gotta avoid eviction, stay out of jail and get to the beach, no matter what.",
    "yt_trailer_code":"9q7g4zz20Kc",
    "language":"English",
    "mpa_rating":"R",
    "background_image":"https://yts.am/assets/images/movies/never_goin_back_2018/background.jpg",
    "background_image_original":"https://yts.am/assets/images/movies/never_goin_back_2018/background.jpg",
    "small_cover_image":"https://yts.am/assets/images/movies/never_goin_back_2018/small-cover.jpg",
    "medium_cover_image":"https://yts.am/assets/images/movies/never_goin_back_2018/medium-cover.jpg",
    "large_cover_image":"https://yts.am/assets/images/movies/never_goin_back_2018/large-cover.jpg",
    "state":"ok",
    "torrents":[  
      {  
          "url":"https://yts.am/torrent/download/364B0C9B8FF56048DC5B7B0BA394031FC21E4048",
          "hash":"364B0C9B8FF56048DC5B7B0BA394031FC21E4048",
          "quality":"720p",
          "seeds":884,
          "peers":651,
          "size":"732.83 MB",
          "size_bytes":768427950,
          "date_uploaded":"2018-10-09 19:29:00",
          "date_uploaded_unix":1539106140
      },
      {  
          "url":"https://yts.am/torrent/download/79E8F6C6009343A7136B89C6D947BD5EB279AA2F",
          "hash":"79E8F6C6009343A7136B89C6D947BD5EB279AA2F",
          "quality":"1080p",
          "seeds":556,
          "peers":294,
          "size":"1.38 GB",
          "size_bytes":1481763717,
          "date_uploaded":"2018-10-09 20:52:40",
          "date_uploaded_unix":1539111160
      }
    ],
    "date_uploaded":"2018-10-09 19:29:00",
    "date_uploaded_unix":1539106140
},
{  
    "id":9255,
    "url":"https://yts.am/movie/light-sleeper-1992",
    "imdb_code":"tt0102307",
    "title":"Light Sleeper",
    "title_english":"Light Sleeper",
    "title_long":"Light Sleeper (1992)",
    "slug":"light-sleeper-1992",
    "year":1992,
    "rating":6.9,
    "runtime":103,
    "genres":[  
      "Crime",
      "Drama"
    ],
    "summary":"A drug dealer with upscale clientele is having moral problems going about his daily deliveries. A reformed addict, he has never gotten over the wife that left him, and the couple that use him for deliveries worry about his mental well-being and his effectiveness at his job. Meanwhile someone is killing women in apparently drug-related incidents.",
    "description_full":"A drug dealer with upscale clientele is having moral problems going about his daily deliveries. A reformed addict, he has never gotten over the wife that left him, and the couple that use him for deliveries worry about his mental well-being and his effectiveness at his job. Meanwhile someone is killing women in apparently drug-related incidents.",
    "synopsis":"A drug dealer with upscale clientele is having moral problems going about his daily deliveries. A reformed addict, he has never gotten over the wife that left him, and the couple that use him for deliveries worry about his mental well-being and his effectiveness at his job. Meanwhile someone is killing women in apparently drug-related incidents.",
    "yt_trailer_code":"YeCwVvBvVcs",
    "language":"English",
    "mpa_rating":"R",
    "background_image":"https://yts.am/assets/images/movies/light_sleeper_1992/background.jpg",
    "background_image_original":"https://yts.am/assets/images/movies/light_sleeper_1992/background.jpg",
    "small_cover_image":"https://yts.am/assets/images/movies/light_sleeper_1992/small-cover.jpg",
    "medium_cover_image":"https://yts.am/assets/images/movies/light_sleeper_1992/medium-cover.jpg",
    "large_cover_image":"https://yts.am/assets/images/movies/light_sleeper_1992/large-cover.jpg",
    "state":"ok",
    "torrents":[  
      {  
          "url":"https://yts.am/torrent/download/2DD475C468D5F25BDFCBC631BBB3E10A3326707E",
          "hash":"2DD475C468D5F25BDFCBC631BBB3E10A3326707E",
          "quality":"720p",
          "seeds":194,
          "peers":86,
          "size":"849.56 MB",
          "size_bytes":890828227,
          "date_uploaded":"2018-10-09 01:07:00",
          "date_uploaded_unix":1539040020
      },
      {  
          "url":"https://yts.am/torrent/download/1973F3687652B593EE8DD6F108AEE4E66788C5C6",
          "hash":"1973F3687652B593EE8DD6F108AEE4E66788C5C6",
          "quality":"1080p",
          "seeds":245,
          "peers":83,
          "size":"1.62 GB",
          "size_bytes":1739461755,
          "date_uploaded":"2018-10-09 03:21:32",
          "date_uploaded_unix":1539048092
      }
    ],
    "date_uploaded":"2018-10-09 01:07:00",
    "date_uploaded_unix":1539040020
},
{  
    "id":9254,
    "url":"https://yts.am/movie/kids-on-the-slope-2018",
    "imdb_code":"tt6835804",
    "title":"Kids on the Slope",
    "title_english":"Kids on the Slope",
    "title_long":"Kids on the Slope (2018)",
    "slug":"kids-on-the-slope-2018",
    "year":2018,
    "rating":7.4,
    "runtime":120,
    "genres":[  
      "Drama"
    ],
    "summary":"Two different students - a successful but aloof academic and a rebellious but kindhearted delinquent - form a friendship through their love for music.",
    "description_full":"Two different students - a successful but aloof academic and a rebellious but kindhearted delinquent - form a friendship through their love for music.",
    "synopsis":"Two different students - a successful but aloof academic and a rebellious but kindhearted delinquent - form a friendship through their love for music.",
    "yt_trailer_code":"Ar7ZegCxDlA",
    "language":"English",
    "mpa_rating":"",
    "background_image":"https://yts.am/assets/images/movies/kids_on_the_slope_2018/background.jpg",
    "background_image_original":"https://yts.am/assets/images/movies/kids_on_the_slope_2018/background.jpg",
    "small_cover_image":"https://yts.am/assets/images/movies/kids_on_the_slope_2018/small-cover.jpg",
    "medium_cover_image":"https://yts.am/assets/images/movies/kids_on_the_slope_2018/medium-cover.jpg",
    "large_cover_image":"https://yts.am/assets/images/movies/kids_on_the_slope_2018/large-cover.jpg",
    "state":"ok",
    "torrents":[  
      {  
          "url":"https://yts.am/torrent/download/DF37317B716B7619B8FE5C08DBB75920FFB2DFF7",
          "hash":"DF37317B716B7619B8FE5C08DBB75920FFB2DFF7",
          "quality":"720p",
          "seeds":235,
          "peers":123,
          "size":"1012.99 MB",
          "size_bytes":1062197002,
          "date_uploaded":"2018-10-08 21:59:42",
          "date_uploaded_unix":1539028782
      },
      {  
          "url":"https://yts.am/torrent/download/D582D472C1394B3F6039EA54BFAA3559A188F7E3",
          "hash":"D582D472C1394B3F6039EA54BFAA3559A188F7E3",
          "quality":"1080p",
          "seeds":256,
          "peers":100,
          "size":"1.91 GB",
          "size_bytes":2050846884,
          "date_uploaded":"2018-10-08 23:55:47",
          "date_uploaded_unix":1539035747
      }
    ],
    "date_uploaded":"2018-10-08 21:59:42",
    "date_uploaded_unix":1539028782
},
{  
    "id":9253,
    "url":"https://yts.am/movie/molly-2017",
    "imdb_code":"tt6522982",
    "title":"Molly",
    "title_english":"Molly",
    "title_long":"Molly (2017)",
    "slug":"molly-2017",
    "year":2017,
    "rating":5.6,
    "runtime":91,
    "genres":[  
      "Action",
      "Sci-Fi"
    ],
    "summary":"In a post apocalyptic world where bullets have become currency and medicine is rare, a clan of marauders uses a home brewed drug to turn innocent people into rabid beasts to have them fight each other in their fighting pits for their entertainment. When their leader discovers rumors of a girl with superpowers roaming the beach near their fort, he sends his best people out to capture her. Meanwhile, the girl, Molly, has discovered a young child, living alone in a cabin in the wasteland, waiting for the return of her parents, who are probably dead. Molly has to protect the child and fight of the marauders at the same time.",
    "description_full":"In a post apocalyptic world where bullets have become currency and medicine is rare, a clan of marauders uses a home brewed drug to turn innocent people into rabid beasts to have them fight each other in their fighting pits for their entertainment. When their leader discovers rumors of a girl with superpowers roaming the beach near their fort, he sends his best people out to capture her. Meanwhile, the girl, Molly, has discovered a young child, living alone in a cabin in the wasteland, waiting for the return of her parents, who are probably dead. Molly has to protect the child and fight of the marauders at the same time.",
    "synopsis":"In a post apocalyptic world where bullets have become currency and medicine is rare, a clan of marauders uses a home brewed drug to turn innocent people into rabid beasts to have them fight each other in their fighting pits for their entertainment. When their leader discovers rumors of a girl with superpowers roaming the beach near their fort, he sends his best people out to capture her. Meanwhile, the girl, Molly, has discovered a young child, living alone in a cabin in the wasteland, waiting for the return of her parents, who are probably dead. Molly has to protect the child and fight of the marauders at the same time.",
    "yt_trailer_code":"bVJWNml_-mE",
    "language":"English",
    "mpa_rating":"",
    "background_image":"https://yts.am/assets/images/movies/molly_2017/background.jpg",
    "background_image_original":"https://yts.am/assets/images/movies/molly_2017/background.jpg",
    "small_cover_image":"https://yts.am/assets/images/movies/molly_2017/small-cover.jpg",
    "medium_cover_image":"https://yts.am/assets/images/movies/molly_2017/medium-cover.jpg",
    "large_cover_image":"https://yts.am/assets/images/movies/molly_2017/large-cover.jpg",
    "state":"ok",
    "torrents":[  
      {  
          "url":"https://yts.am/torrent/download/C7D9D01284DEB0074A84FEEF27E1E5E3562CA918",
          "hash":"C7D9D01284DEB0074A84FEEF27E1E5E3562CA918",
          "quality":"720p",
          "seeds":541,
          "peers":371,
          "size":"812.8 MB",
          "size_bytes":852282573,
          "date_uploaded":"2018-10-09 02:13:02",
          "date_uploaded_unix":1539043982
      },
      {  
          "url":"https://yts.am/torrent/download/8E1161BB858C78191ECF64CF17814F49498FFBD3",
          "hash":"8E1161BB858C78191ECF64CF17814F49498FFBD3",
          "quality":"1080p",
          "seeds":446,
          "peers":170,
          "size":"1.52 GB",
          "size_bytes":1632087572,
          "date_uploaded":"2018-10-09 04:13:28",
          "date_uploaded_unix":1539051208
      }
    ],
    "date_uploaded":"2018-10-09 02:13:02",
    "date_uploaded_unix":1539043982
},
{  
    "id":9252,
    "url":"https://yts.am/movie/the-happy-prince-2018",
    "imdb_code":"tt2404639",
    "title":"The Happy Prince",
    "title_english":"The Happy Prince",
    "title_long":"The Happy Prince (2018)",
    "slug":"the-happy-prince-2018",
    "year":2018,
    "rating":6.5,
    "runtime":105,
    "genres":[  
      "Biography",
      "Drama"
    ],
    "summary":"In a cheap Parisian hotel room Oscar Wilde lies on his death bed. The past floods back, taking him to other times and places. Was he once the most famous man in London? The artist crucified by a society that once worshipped him? Under the microscope of death he reviews the failed attempt to reconcile with his long suffering wife Constance, the ensuing reprisal of his fatal love affair with Lord Alfred Douglas and the warmth and devotion of Robbie Ross, who tried and failed to save him from himself. Travelling through Wilde's final act and journeys through England, France and Italy, the transience of lust is laid bare and the true riches of love are revealed. It is a portrait of the dark side of a genius who lived and died for love.",
    "description_full":"In a cheap Parisian hotel room Oscar Wilde lies on his death bed. The past floods back, taking him to other times and places. Was he once the most famous man in London? The artist crucified by a society that once worshipped him? Under the microscope of death he reviews the failed attempt to reconcile with his long suffering wife Constance, the ensuing reprisal of his fatal love affair with Lord Alfred Douglas and the warmth and devotion of Robbie Ross, who tried and failed to save him from himself. Travelling through Wilde's final act and journeys through England, France and Italy, the transience of lust is laid bare and the true riches of love are revealed. It is a portrait of the dark side of a genius who lived and died for love.",
    "synopsis":"In a cheap Parisian hotel room Oscar Wilde lies on his death bed. The past floods back, taking him to other times and places. Was he once the most famous man in London? The artist crucified by a society that once worshipped him? Under the microscope of death he reviews the failed attempt to reconcile with his long suffering wife Constance, the ensuing reprisal of his fatal love affair with Lord Alfred Douglas and the warmth and devotion of Robbie Ross, who tried and failed to save him from himself. Travelling through Wilde's final act and journeys through England, France and Italy, the transience of lust is laid bare and the true riches of love are revealed. It is a portrait of the dark side of a genius who lived and died for love.",
    "yt_trailer_code":"4HmN9r1Fcr8",
    "language":"English",
    "mpa_rating":"R",
    "background_image":"https://yts.am/assets/images/movies/the_happy_prince_2018/background.jpg",
    "background_image_original":"https://yts.am/assets/images/movies/the_happy_prince_2018/background.jpg",
    "small_cover_image":"https://yts.am/assets/images/movies/the_happy_prince_2018/small-cover.jpg",
    "medium_cover_image":"https://yts.am/assets/images/movies/the_happy_prince_2018/medium-cover.jpg",
    "large_cover_image":"https://yts.am/assets/images/movies/the_happy_prince_2018/large-cover.jpg",
    "state":"ok",
    "torrents":[  
      {  
          "url":"https://yts.am/torrent/download/8E3ED31E82C4620F3FB8F747986F8BCD2CCB956F",
          "hash":"8E3ED31E82C4620F3FB8F747986F8BCD2CCB956F",
          "quality":"720p",
          "seeds":446,
          "peers":264,
          "size":"890.06 MB",
          "size_bytes":933295555,
          "date_uploaded":"2018-10-08 23:19:50",
          "date_uploaded_unix":1539033590
      },
      {  
          "url":"https://yts.am/torrent/download/0E3C958A70A2E5103474375BE4C732FA5F7D8238",
          "hash":"0E3C958A70A2E5103474375BE4C732FA5F7D8238",
          "quality":"1080p",
          "seeds":430,
          "peers":164,
          "size":"1.68 GB",
          "size_bytes":1803886264,
          "date_uploaded":"2018-10-09 01:09:19",
          "date_uploaded_unix":1539040159
      }
    ],
    "date_uploaded":"2018-10-08 23:19:50",
    "date_uploaded_unix":1539033590
},
{  
    "id":9251,
    "url":"https://yts.am/movie/flight-of-the-living-dead-2007",
    "imdb_code":"tt0780583",
    "title":"Flight of the Living Dead",
    "title_english":"Flight of the Living Dead",
    "title_long":"Flight of the Living Dead (2007)",
    "slug":"flight-of-the-living-dead-2007",
    "year":2007,
    "rating":5.2,
    "runtime":94,
    "genres":[  
      "Action",
      "Horror",
      "Sci-Fi"
    ],
    "summary":"A fellow scientist accidentally escapes containment aboard a plane during turbulence. After she is gunned down by a security guard, she reanimates as a zombie, killing and infecting several passengers and crew members on board the flight. A U.S. federal air marshall, along with a police officer, a flight attendant and a handful of survivors, must ride out the horrific flight just long enough to stay alive.",
    "description_full":"A fellow scientist accidentally escapes containment aboard a plane during turbulence. After she is gunned down by a security guard, she reanimates as a zombie, killing and infecting several passengers and crew members on board the flight. A U.S. federal air marshall, along with a police officer, a flight attendant and a handful of survivors, must ride out the horrific flight just long enough to stay alive.",
    "synopsis":"A fellow scientist accidentally escapes containment aboard a plane during turbulence. After she is gunned down by a security guard, she reanimates as a zombie, killing and infecting several passengers and crew members on board the flight. A U.S. federal air marshall, along with a police officer, a flight attendant and a handful of survivors, must ride out the horrific flight just long enough to stay alive.",
    "yt_trailer_code":"2yxnJ6c1IKk",
    "language":"English",
    "mpa_rating":"",
    "background_image":"https://yts.am/assets/images/movies/flight_of_the_living_dead_2007/background.jpg",
    "background_image_original":"https://yts.am/assets/images/movies/flight_of_the_living_dead_2007/background.jpg",
    "small_cover_image":"https://yts.am/assets/images/movies/flight_of_the_living_dead_2007/small-cover.jpg",
    "medium_cover_image":"https://yts.am/assets/images/movies/flight_of_the_living_dead_2007/medium-cover.jpg",
    "large_cover_image":"https://yts.am/assets/images/movies/flight_of_the_living_dead_2007/large-cover.jpg",
    "state":"ok",
    "torrents":[  
      {  
          "url":"https://yts.am/torrent/download/B46E026FC6807D8BC5FE22E7386269D129FE8BA8",
          "hash":"B46E026FC6807D8BC5FE22E7386269D129FE8BA8",
          "quality":"720p",
          "seeds":235,
          "peers":149,
          "size":"804.03 MB",
          "size_bytes":843086561,
          "date_uploaded":"2018-10-08 20:01:43",
          "date_uploaded_unix":1539021703
      },
      {  
          "url":"https://yts.am/torrent/download/B5F62E152E7A9D90238BFD3DBD08050A48A8A183",
          "hash":"B5F62E152E7A9D90238BFD3DBD08050A48A8A183",
          "quality":"1080p",
          "seeds":204,
          "peers":63,
          "size":"1.51 GB",
          "size_bytes":1621350154,
          "date_uploaded":"2018-10-08 22:22:43",
          "date_uploaded_unix":1539030163
      }
    ],
    "date_uploaded":"2018-10-08 20:01:43",
    "date_uploaded_unix":1539021703
},
{  
    "id":9250,
    "url":"https://yts.am/movie/penguin-rescue-2018",
    "imdb_code":"tt7575480",
    "title":"Penguin Rescue",
    "title_english":"Penguin Rescue",
    "title_long":"Penguin Rescue (2018)",
    "slug":"penguin-rescue-2018",
    "year":2018,
    "rating":0,
    "runtime":0,
    "genres":[  
      "Action"
    ],
    "summary":"",
    "description_full":"",
    "synopsis":"",
    "yt_trailer_code":"",
    "language":"English",
    "mpa_rating":"",
    "background_image":"https://yts.am/assets/images/movies/penguin_rescue_2018/background.jpg",
    "background_image_original":"https://yts.am/assets/images/movies/penguin_rescue_2018/background.jpg",
    "small_cover_image":"https://yts.am/assets/images/movies/penguin_rescue_2018/small-cover.jpg",
    "medium_cover_image":"https://yts.am/assets/images/movies/penguin_rescue_2018/medium-cover.jpg",
    "large_cover_image":"https://yts.am/assets/images/movies/penguin_rescue_2018/large-cover.jpg",
    "state":"ok",
    "torrents":[  
      {  
          "url":"https://yts.am/torrent/download/D8578A24AF9AEC2DC28EC612D32BB26E7227DB65",
          "hash":"D8578A24AF9AEC2DC28EC612D32BB26E7227DB65",
          "quality":"720p",
          "seeds":435,
          "peers":244,
          "size":"593.29 MB",
          "size_bytes":622109655,
          "date_uploaded":"2018-10-08 17:24:31",
          "date_uploaded_unix":1539012271
      },
      {  
          "url":"https://yts.am/torrent/download/EFDE961DC2B742FFA7443E904751A4A5AF06A004",
          "hash":"EFDE961DC2B742FFA7443E904751A4A5AF06A004",
          "quality":"1080p",
          "seeds":320,
          "peers":165,
          "size":"1.12 GB",
          "size_bytes":1202590843,
          "date_uploaded":"2018-10-08 18:43:20",
          "date_uploaded_unix":1539017000
      }
    ],
    "date_uploaded":"2018-10-08 17:24:31",
    "date_uploaded_unix":1539012271
},
{  
    "id":9249,
    "url":"https://yts.am/movie/circus-kane-2017",
    "imdb_code":"tt6164014",
    "title":"Circus Kane",
    "title_english":"Circus Kane",
    "title_long":"Circus Kane (2017)",
    "slug":"circus-kane-2017",
    "year":2017,
    "rating":4.6,
    "runtime":88,
    "genres":[  
      "Horror"
    ],
    "summary":"A reclusive circus master invites a group of social media stars to his house of haunts. Anyone who can make it out before being scared into submission will earn $250,000 - but the stars soon learn they are not only competing for money, but also fighting for their lives.",
    "description_full":"A reclusive circus master invites a group of social media stars to his house of haunts. Anyone who can make it out before being scared into submission will earn $250,000 - but the stars soon learn they are not only competing for money, but also fighting for their lives.",
    "synopsis":"A reclusive circus master invites a group of social media stars to his house of haunts. Anyone who can make it out before being scared into submission will earn $250,000 - but the stars soon learn they are not only competing for money, but also fighting for their lives.",
    "yt_trailer_code":"bMrSwT3NKV8",
    "language":"English",
    "mpa_rating":"",
    "background_image":"https://yts.am/assets/images/movies/circus_kane_2017/background.jpg",
    "background_image_original":"https://yts.am/assets/images/movies/circus_kane_2017/background.jpg",
    "small_cover_image":"https://yts.am/assets/images/movies/circus_kane_2017/small-cover.jpg",
    "medium_cover_image":"https://yts.am/assets/images/movies/circus_kane_2017/medium-cover.jpg",
    "large_cover_image":"https://yts.am/assets/images/movies/circus_kane_2017/large-cover.jpg",
    "state":"ok",
    "torrents":[  
      {  
          "url":"https://yts.am/torrent/download/331BB365C410D7B78812C60D0B226BB5A34137B1",
          "hash":"331BB365C410D7B78812C60D0B226BB5A34137B1",
          "quality":"720p",
          "seeds":232,
          "peers":114,
          "size":"755.69 MB",
          "size_bytes":792398397,
          "date_uploaded":"2018-10-08 14:56:52",
          "date_uploaded_unix":1539003412
      },
      {  
          "url":"https://yts.am/torrent/download/23260B676C10ABEC60682C43F3934EAD027B5A69",
          "hash":"23260B676C10ABEC60682C43F3934EAD027B5A69",
          "quality":"1080p",
          "seeds":169,
          "peers":67,
          "size":"1.42 GB",
          "size_bytes":1524713390,
          "date_uploaded":"2018-10-08 16:42:55",
          "date_uploaded_unix":1539009775
      }
    ],
    "date_uploaded":"2018-10-08 14:56:52",
    "date_uploaded_unix":1539003412
},
{  
    "id":9248,
    "url":"https://yts.am/movie/the-trial-of-billy-jack-1974",
    "imdb_code":"tt0072317",
    "title":"The Trial of Billy Jack",
    "title_english":"The Trial of Billy Jack",
    "title_long":"The Trial of Billy Jack (1974)",
    "slug":"the-trial-of-billy-jack-1974",
    "year":1974,
    "rating":4.7,
    "runtime":170,
    "genres":[  
      "Action",
      "Drama",
      "Music",
      "Thriller"
    ],
    "summary":"After Billy Jack in sentenced to four years in prison for the \"involuntary manslaughter\" of the first film, the Freedom School expands and flourishes under the guidance of Jean Roberts. The utopian existence of the school is characterized by everything ranging from \"yoga sports\" to muckracking journalism. The diverse student population airs scathing political exposes on their privately owned television station. The narrow-minded townspeople have different ideas about their brand of liberalism. Billy Jack is released and things heat up for the school. Students are threatened and abused and the Native Americans in the neighboring village are taunted and mistreated. After Billy Jack undergoes a vision quest, the governor and the police plot to permanently put an end to their liberal shenanigans, leaving it up to Billy Jack to save the day.",
    "description_full":"After Billy Jack in sentenced to four years in prison for the \"involuntary manslaughter\" of the first film, the Freedom School expands and flourishes under the guidance of Jean Roberts. The utopian existence of the school is characterized by everything ranging from \"yoga sports\" to muckracking journalism. The diverse student population airs scathing political exposes on their privately owned television station. The narrow-minded townspeople have different ideas about their brand of liberalism. Billy Jack is released and things heat up for the school. Students are threatened and abused and the Native Americans in the neighboring village are taunted and mistreated. After Billy Jack undergoes a vision quest, the governor and the police plot to permanently put an end to their liberal shenanigans, leaving it up to Billy Jack to save the day.",
    "synopsis":"After Billy Jack in sentenced to four years in prison for the \"involuntary manslaughter\" of the first film, the Freedom School expands and flourishes under the guidance of Jean Roberts. The utopian existence of the school is characterized by everything ranging from \"yoga sports\" to muckracking journalism. The diverse student population airs scathing political exposes on their privately owned television station. The narrow-minded townspeople have different ideas about their brand of liberalism. Billy Jack is released and things heat up for the school. Students are threatened and abused and the Native Americans in the neighboring village are taunted and mistreated. After Billy Jack undergoes a vision quest, the governor and the police plot to permanently put an end to their liberal shenanigans, leaving it up to Billy Jack to save the day.",
    "yt_trailer_code":"cKpFt-fLyVE",
    "language":"English",
    "mpa_rating":"",
    "background_image":"https://yts.am/assets/images/movies/the_trial_of_billy_jack_1974/background.jpg",
    "background_image_original":"https://yts.am/assets/images/movies/the_trial_of_billy_jack_1974/background.jpg",
    "small_cover_image":"https://yts.am/assets/images/movies/the_trial_of_billy_jack_1974/small-cover.jpg",
    "medium_cover_image":"https://yts.am/assets/images/movies/the_trial_of_billy_jack_1974/medium-cover.jpg",
    "large_cover_image":"https://yts.am/assets/images/movies/the_trial_of_billy_jack_1974/large-cover.jpg",
    "state":"ok",
    "torrents":[  
      {  
          "url":"https://yts.am/torrent/download/A7A864CD4E202FDA334CF5747AF7160389576D23",
          "hash":"A7A864CD4E202FDA334CF5747AF7160389576D23",
          "quality":"720p",
          "seeds":73,
          "peers":38,
          "size":"1.36 GB",
          "size_bytes":1460288881,
          "date_uploaded":"2018-10-08 17:16:35",
          "date_uploaded_unix":1539011795
      },
      {  
          "url":"https://yts.am/torrent/download/213E514443266A433E1E69DD855E376F708E3135",
          "hash":"213E514443266A433E1E69DD855E376F708E3135",
          "quality":"1080p",
          "seeds":114,
          "peers":42,
          "size":"2.67 GB",
          "size_bytes":2866890670,
          "date_uploaded":"2018-10-08 20:58:10",
          "date_uploaded_unix":1539025090
      }
    ],
    "date_uploaded":"2018-10-08 17:16:35",
    "date_uploaded_unix":1539011795
},
{  
    "id":9247,
    "url":"https://yts.am/movie/the-outlaw-1943",
    "imdb_code":"tt0036241",
    "title":"The Outlaw",
    "title_english":"The Outlaw",
    "title_long":"The Outlaw (1943)",
    "slug":"the-outlaw-1943",
    "year":1943,
    "rating":5.5,
    "runtime":116,
    "genres":[  
      "Comedy",
      "Drama",
      "Romance",
      "Western"
    ],
    "summary":"Newly appointed sheriff Pat Garrett is pleased when his old friend Doc Holliday arrives in Lincoln, New Mexico on the stage. Doc is trailing his stolen horse, and it is discovered in the possession of Billy the Kid. In a surprising turnaround, Billy and Doc become friends. This causes the friendship between Doc and Pat to cool. The odd relationship between Doc and Billy grows stranger when Doc hides Billy at his girl, Rio's, place after Billy is shot. She falls for Billy, although he treats her very badly. Interaction between these four is played out against an Indian attack before a final showdown reduces the group's number.",
    "description_full":"Newly appointed sheriff Pat Garrett is pleased when his old friend Doc Holliday arrives in Lincoln, New Mexico on the stage. Doc is trailing his stolen horse, and it is discovered in the possession of Billy the Kid. In a surprising turnaround, Billy and Doc become friends. This causes the friendship between Doc and Pat to cool. The odd relationship between Doc and Billy grows stranger when Doc hides Billy at his girl, Rio's, place after Billy is shot. She falls for Billy, although he treats her very badly. Interaction between these four is played out against an Indian attack before a final showdown reduces the group's number.",
    "synopsis":"Newly appointed sheriff Pat Garrett is pleased when his old friend Doc Holliday arrives in Lincoln, New Mexico on the stage. Doc is trailing his stolen horse, and it is discovered in the possession of Billy the Kid. In a surprising turnaround, Billy and Doc become friends. This causes the friendship between Doc and Pat to cool. The odd relationship between Doc and Billy grows stranger when Doc hides Billy at his girl, Rio's, place after Billy is shot. She falls for Billy, although he treats her very badly. Interaction between these four is played out against an Indian attack before a final showdown reduces the group's number.",
    "yt_trailer_code":"Gnjv3ONSa9o",
    "language":"English",
    "mpa_rating":"",
    "background_image":"https://yts.am/assets/images/movies/the_outlaw_1943/background.jpg",
    "background_image_original":"https://yts.am/assets/images/movies/the_outlaw_1943/background.jpg",
    "small_cover_image":"https://yts.am/assets/images/movies/the_outlaw_1943/small-cover.jpg",
    "medium_cover_image":"https://yts.am/assets/images/movies/the_outlaw_1943/medium-cover.jpg",
    "large_cover_image":"https://yts.am/assets/images/movies/the_outlaw_1943/large-cover.jpg",
    "state":"ok",
    "torrents":[  
      {  
          "url":"https://yts.am/torrent/download/2DE343F2800A5EEC68123A5ABDE232220715CA9B",
          "hash":"2DE343F2800A5EEC68123A5ABDE232220715CA9B",
          "quality":"720p",
          "seeds":65,
          "peers":34,
          "size":"944.26 MB",
          "size_bytes":990128374,
          "date_uploaded":"2018-10-08 13:18:14",
          "date_uploaded_unix":1538997494
      },
      {  
          "url":"https://yts.am/torrent/download/07931AC9C183D556CCB1ABA3C27B918CAB339D3F",
          "hash":"07931AC9C183D556CCB1ABA3C27B918CAB339D3F",
          "quality":"1080p",
          "seeds":105,
          "peers":38,
          "size":"1.81 GB",
          "size_bytes":1943472701,
          "date_uploaded":"2018-10-08 15:20:05",
          "date_uploaded_unix":1539004805
      }
    ],
    "date_uploaded":"2018-10-08 13:18:14",
    "date_uploaded_unix":1538997494
}
]
